In [1]:
# Importando bibliotecas necessárias
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
from pathlib import Path
import os
import sys

sys.path.append(os.path.abspath("../src"))

import warnings

warnings.filterwarnings("ignore")

# Configurações de visualização
pio.templates.default = "plotly_white"
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_rows", 50)
# set default to plotly in pandas
pd.options.plotting.backend = "plotly"

In [2]:
df = pd.read_excel("../data/raw/20260505-data_neophilic_gardener.xlsx", header=None)
# Use the last row as header
df.columns = df.iloc[-1]
df = df[:-1]
df.reset_index(drop=True, inplace=True)
df

191,id,date_birth,zip_code,urbanization_degree,gender,education_level,education_field,gardener,garden_type_communitary,garden_type_pedagogical,garden_type_other,garden_type_other_description,years_experience,frequency_experience,experience_description,G03Q11,G03Q12,G03Q13,G03Q14,G03Q15,G03Q16,G03Q17,G03Q18,G03Q19,G03Q20,recognition_grade,G03Q21,G03Q22,G03Q23,G03Q24,G03Q25,G03Q26,G03Q27,G03Q28,G03Q29,G03Q30,classification_grade,recall_plants,plants_valid,plants_total,recall_algae,algae_valid,algae_total,recall_mushrooms,mushrooms_valid,mushrooms_total,species_total,diet_type,consumption_plants_time_scale,consumption_plants_frequency,consumption_mushrooms_time_scale,consumption_mushrooms_frequency,consumption_algae_time_scale,consumption_algae_frequency,social_model_plants,social_model_mushrooms,social_model_algae,social_model_other,social_trigger_plants,social_trigger_mushrooms,social_trigger_algae,meals_friends,meals_family_older,meals_family_same_generation,meals_not_family_older,barrier_plant,barrier_mushroom,barrier_algae,barrier_other,G06Q39,G06Q40,G06Q41,G06Q42,G06Q43,G06Q44,G06Q45,G06Q46,G06Q47,G06Q48,G06Q49,G06Q50,G06Q51,G06Q52,extra_info,authorization_new_contact,interview_time
0,15,1986,59082110,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Mestrado concluído,Ciências Biológicas,Sim,Não,Sim,Não,NaN,0,1,"Participei de algumas oficinas, mas não tive c...",Nori,Não sei,Não sei,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,8,Alga,Não sei,Não sei,Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",8,"rambutan, cupuaçu, mangostim, pitaya, almeirão...","rambutan, cupuaçu, mangostim, pitaya, almeirão...",6,As algas que conheço já foram mencionadas nest...,0,0,Os cogumelos que conheço já foram mencionados ...,0,0,6,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Mês,1,Mês,2,Não consumi ou consumo esse tipo de alimento,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,NaN,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,0,0,16,0,Falta de conhecimento: não conheço esses alime...,Falta de acesso econômico: acho esse tipo de a...,Falta de acesso econômico: acho esse tipo de a...,NaN,1 - Discordo totalmente,1 - Discordo totalmente,1 - Discordo totalmente,1 - Discordo totalmente,6 - Concordo bastante,5 - Concordo pouco,1 - Discordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,5 - Concordo pouco,NaN,NaN,NaN,NaN,Me considero uma pessoa muito interessada em n...,"Sim, podem me contatar!",NaN
1,17,1997,59090324,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Mestrado concluído,Nutrição,Sim,Sim,Sim,Não,NaN,7,5,"Participei de atividades de ensino, pesquisa e...",Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",9,"Urucum, taioba, ora-pro-nobis,fruta pão,jambú,...","urucum, ora-pro-nóbis, fruta-pão, jambu, cubiu...",14,Alga nori,0,0,"Shitake,shimeji, portubelo, champignon",0,0,14,Flexitariano - Tenho um cardápio flexível e co...,Semana,1,Mês,1,Mês,1,Professores ou pessoas de referência mais velh...,Familiares da mesma idade ou mais novos do que eu,Não consumi ou consumo esse tipo de alimento,NaN,Familiares da mesma idade ou mais novos do que eu,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,3,2,0,2,Falta de acesso físico: não é fácil de achar e...,Outro,Outro,NaN,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,"4 - Nem discordo, nem concordo",7 - Concordo totalmente,2 - Discordo bastante,7 - Concordo totalmente,6 - Concordo bastante,6 - Concordo bastante,6 - Concordo bastante,1 - Discordo totalmente,NaN,"Sim, podem me contatar!",NaN
2,19,1993,53200000,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Mestrado em curso,Ciências Biológicas,Sim,Não,Sim,Não,NaN,1,3,Já respondi,Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",10,Já respondi,"couvinha, monguba, margaridinha-cosmos, ararut...",17,Já respondi,0,0,Já respondi,"orelha-de-judas, ostra-rosa, porcini",3,20,Onívora - Possuo uma alimentação diversificada...,Ano,5,Ano,1,Ano,3,Familiares mais velhos que eu,Outro,Outro,"No tempo que fui vegetariana pesquisei, por co...",Meus amigos ou colegas de trabalho,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,3,7,0,0,Falta de acesso físico: não é fácil de achar e...,Falta de acesso econômico: acho esse tipo de a...,Falta de acesso físico: não é fácil de achar e...,NaN,6 - Concordo bastante,1 - Discordo totalmente,3 - Discordo pouco,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,1 - Discordo totalmente,2 - Discordo bastante,6 - Concordo bastante,7 - Concordo totalmente,NaN,NaN,NaN,NaN,NaN,"Sim, podem me contatar!",NaN
3,20,1996,59078350,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação concluída,Ecologia,Sim,Sim,Sim,Não,NaN,2,5,Durante meu envolvimento com a Horta Comunitár...,Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",10,"Mastruz, couvinha, beldroega, cariru, bredo, c...","mastruz, couvinha, major-gomes, caruru, chanan...",11,"Nori, wakame, kombu, hijiki",hijiki,1,"Shimeji, Champignon, Shitake, Portobello",0,0,12,Vegana - Não me alimento de nenhum produto que...,Ano,3,Ano,3,Ano,3,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,1,1,0,0,Falta de acesso físico: não é fácil de achar e...,Falta de acesso físico: não é fácil de achar e...,Falta de acesso físico: não é fácil de achar e...,NaN,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,"4 - Nem discordo, nem concordo",5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,5 - Concordo pouco,3 - Discordo pouco,Experimentar alimentos novos e sabores diferen...,"Sim, podem me contatar!",NaN
4,21,1994,59054831,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Doutorado em curso,Nutrição,Sim,Sim,Sim,Não,NaN,2,5,Respondido anteriormente.,Nori,Beldroega,Não sei,Shitake,Portobello,Não sei,Não sei,Taioba,Shimeji,Mangaba,7,Alga,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",7,Respondido anteriormente.,"couvinha, major-gomes, urucum, moringa, ora-pr...",11,Respondido anteriormente.,0,0,Respondido anteriormente.,0,0,11,Onívora - Possuo uma alimentação diversificada...,Ano,5,Ano,10,Semana,2,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,5,11,3,5,Outro,Falta de acesso econômico: acho esse tipo de a...,Outro,"Gosto, mas não tenho o hábito de fazer prepara...",6 - Concordo bastante,1 - Discordo totalmente,2 - Discordo bastante,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,2 - Discordo bastante,3 - Discordo pouco,6 - Concordo bastante,7 - Concordo totalmente,2 - Discordo bastante,6 - Concordo bastante,6 - Concordo bastante,2 - Discordo bastante,Minha convivência com a horta mudou muito o me...,"Sim, podem me contatar!",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,511,2004,59074721,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação em curso,Estou cursando nutrição,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Tucumã,Não sei,Não sei,Não sei,Não sei,Taioba,Não sei,Mangaba,3,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,Não me recordo de nenhuma,NaN,0,Não conheço,NaN,0,Champingnon,NaN,0,0,Onívora - Possuo uma alimentação diversificada...,Mês,1,Nenhum,0,Nenhum,0,Meus amigos ou colegas de trabalho,Não consumi ou consumo esse tipo de alimento,Não consumi ou consumo esse tipo de alimento,NaN,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,3,3,3,0,Falta de acesso físico: não é fácil de achar e...,Outro,Outro,Não me atrai a ideia de comê-los.,5 - Concordo pouco,5 - Concordo pouco,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,"4 - Nem discordo, nem concordo",NaN,NaN,NaN,NaN,NaN,"Não, prefiro não ser contatado novamente.",NaN
187,512,2008,59158400,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação em curso,Nutrição,Sim,Não,Sim,Não,NaN,0,1,O primeiro contato de verdade que tive com hor...,Não sei,Não sei,Não sei,Shitake,Não sei,Não sei,Não sei,Não sei,Shimeji,Mangaba,3,Não sei,Não sei,Não sei,Cogumelo,Não sei,Não sei,Não sei,Não sei,Cogumelo,"Planta - incluindo frutas, verduras e legumes",3,Clitória.,clitória,1,Não conheço,NaN,0,Não conheço,NaN,0,1,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Nenhum,0,Nenhum,0,Não consumi ou consumo esse tipo de alimento,Não consumi ou consumo esse tipo de alimento,Não consumi ou consumo esse tipo de alimento,NaN,Professores ou pessoas de referência mais velh...,Familiares mais velhos que eu,Meus amigos ou colegas de trabalho,1,7,0,0,Falta de conhecimento: não conheço esses alime...,Falta de conhecimento: não conheço esses alime...,Falta de conhecimento: não conheço esses alime...,NaN,5 - Concordo pouco,3 - Discordo pouco,6 - Concordo bastante,"4 - Nem discordo, nem concordo",1 - Discordo totalmente,7 - Concordo totalmente,2 - Discordo bastante,5 - Concordo pouco,5 - Concordo pouco,7 - Concordo totalmente,NaN,NaN,NaN,NaN,Não me senti muito bem ao sentir a textura um ...,"Sim, podem me contatar!",NaN
188,513,2007,59082180,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Graduação em curso,Cursando Nutrição.,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Não sei,Não sei,Coprinellus,Não sei,Não sei,Taioba,Shimeji,Mangaba,3,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Alga,Cogumelo,Alga,Cogumelo,"Planta - incluindo frutas, verduras e legumes",Alga,"Planta - incluindo frutas, verduras e legumes",7,"Taioba, ora-pra-nos, xanana.","chanana, ora-pro-nóbis",2,Não conheço algas.,NaN,0,Não tenho conhecimento sobre cogumelos.,NaN,0,2,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Nenhum,0,Ano,10,Meus amigos ou colegas de trabalho,Familiares mais velhos que eu,Familiares da mesma idade ou mais novos do que eu,NaN,Professores ou pessoas de referência mais velh...,Familiares mais velhos que eu,Familiares mais velhos que eu,4,2,0,0,Falta de conhecimento: não conheço esses alime...,Não consumo porque não tenho intenção,Falta de acesso econômico: acho esse tipo de a...,NaN,3 - Discordo pouco,5 - Concordo pouco,2 - Discordo bastante,5 - Concordo pouco,3 - Discordo pouco,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,3 - Discordo pouco,2 - Discordo bastante,NaN,NaN,NaN,NaN,NaN,"Sim, podem me contatar!",NaN
189,515,2001,59151903,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação em curso,Nutrição,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Tervina,Tucumã,Não sei,Não sei,Não sei,Não sei,Taioba,Não sei,Mangaba,3,Alga,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Não sei,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,Umbu\n Seriguela\n Mangaba,"umbu, seriguela",2,Nori\n Spirulina,spirulina,1,Champignon,NaN,0,3,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Nenhum,0,Nenhum,0,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,2,0,0,0,Falta de conhecimento: não conheço esses alime...,Não consumo porque não tenho intenção,Não consumo porque não tenho intenção,NaN,1 - Discordo totalmente,"4 - Nem discordo, nem concordo",6 - Concordo bastante,2 - Discordo bastante,5 - Concordo pouco,1 - Discordo totalmente,6 - Concordo bastante,5 - Concordo pouco,3 - Discordo pouco,3 - Discordo pouco,NaN,NaN,NaN,NaN,Minha relação com alimentos negligenciados ain...,"Sim, podem me contatar!",NaN
190,519,1998,59088750,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Mestrado em curso,ciências sociais,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Não sei,Não sei,Coprinellus,Não sei,Não sei,Não sei,Não sei,Mangaba,1,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,não lembro,NaN,0,não conheço,NaN,0,não conheço,NaN,0,0,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Ano,2,Nenhum,0,Não consumi ou consumo esse tipo de alimento,Familiares mais velhos que eu,Não consumi ou consumo esse tipo de alimento,NaN,Familiares mais velhos que eu,Familiares mais velhos que eu,Familiares mais velhos que eu,0,3,0,0,Falta de conhecimento: não conheço esses alime...,Falta de acesso físico: não é fácil de achar e...,Falta de conhecimento: não conheço esses alime...,NaN,3 - Discordo pouco,2 - Discordo bastante,2 - Discordo bastante,5 - Concordo pouco,2 - Discordo bastante,6 - Concordo bastante,"4 - Nem discordo, nem concordo",5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,NaN,NaN,NaN,NaN,Não tenho o costume de refletir sobre hábitos ...,"Sim, podem me contatar!",NaN

In [3]:
df.shape

(191, 86)

In [4]:
import re
import unicodedata

# Limpando os nomes das colunas para remover espaços e caracteres especiais
print("Cleaning column names...")


# Função para limpar nomes de colunas
def clean_col_names(df):
    cols = df.columns
    new_cols = []
    for col in cols:
        # Remove espaços no início/fim, substitui espaços internos por _, e converte para minúsculas
        new_col = re.sub(r"\s+", "_", col.strip()).lower()
        new_col = re.sub(r"[^\w]", "", new_col)  # Remove caracteres especiais
        new_col = unicodedata.normalize("NFKD", new_col).encode("ASCII", "ignore").decode("utf-8")  # Remove acentuação
        new_cols.append(new_col)
    df.columns = new_cols
    return df


df = clean_col_names(df)
df.head(5)

Cleaning column names...

,id,date_birth,zip_code,urbanization_degree,gender,education_level,education_field,gardener,garden_type_communitary,garden_type_pedagogical,garden_type_other,garden_type_other_description,years_experience,frequency_experience,experience_description,g03q11,g03q12,g03q13,g03q14,g03q15,g03q16,g03q17,g03q18,g03q19,g03q20,recognition_grade,g03q21,g03q22,g03q23,g03q24,g03q25,g03q26,g03q27,g03q28,g03q29,g03q30,classification_grade,recall_plants,plants_valid,plants_total,recall_algae,algae_valid,algae_total,recall_mushrooms,mushrooms_valid,mushrooms_total,species_total,diet_type,consumption_plants_time_scale,consumption_plants_frequency,consumption_mushrooms_time_scale,consumption_mushrooms_frequency,consumption_algae_time_scale,consumption_algae_frequency,social_model_plants,social_model_mushrooms,social_model_algae,social_model_other,social_trigger_plants,social_trigger_mushrooms,social_trigger_algae,meals_friends,meals_family_older,meals_family_same_generation,meals_not_family_older,barrier_plant,barrier_mushroom,barrier_algae,barrier_other,g06q39,g06q40,g06q41,g06q42,g06q43,g06q44,g06q45,g06q46,g06q47,g06q48,g06q49,g06q50,g06q51,g06q52,extra_info,authorization_new_contact,interview_time
0,15,1986,59082110,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Mestrado concluído,Ciências Biológicas,Sim,Não,Sim,Não,NaN,0,1,"Participei de algumas oficinas, mas não tive c...",Nori,Não sei,Não sei,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,8,Alga,Não sei,Não sei,Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",8,"rambutan, cupuaçu, mangostim, pitaya, almeirão...","rambutan, cupuaçu, mangostim, pitaya, almeirão...",6,As algas que conheço já foram mencionadas nest...,0,0,Os cogumelos que conheço já foram mencionados ...,0,0,6,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Mês,1,Mês,2,Não consumi ou consumo esse tipo de alimento,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,NaN,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,0,0,16,0,Falta de conhecimento: não conheço esses alime...,Falta de acesso econômico: acho esse tipo de a...,Falta de acesso econômico: acho esse tipo de a...,NaN,1 - Discordo totalmente,1 - Discordo totalmente,1 - Discordo totalmente,1 - Discordo totalmente,6 - Concordo bastante,5 - Concordo pouco,1 - Discordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,5 - Concordo pouco,NaN,NaN,NaN,NaN,Me considero uma pessoa muito interessada em n...,"Sim, podem me contatar!",NaN
1,17,1997,59090324,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Mestrado concluído,Nutrição,Sim,Sim,Sim,Não,NaN,7,5,"Participei de atividades de ensino, pesquisa e...",Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",9,"Urucum, taioba, ora-pro-nobis,fruta pão,jambú,...","urucum, ora-pro-nóbis, fruta-pão, jambu, cubiu...",14,Alga nori,0,0,"Shitake,shimeji, portubelo, champignon",0,0,14,Flexitariano - Tenho um cardápio flexível e co...,Semana,1,Mês,1,Mês,1,Professores ou pessoas de referência mais velh...,Familiares da mesma idade ou mais novos do que eu,Não consumi ou consumo esse tipo de alimento,NaN,Familiares da mesma idade ou mais novos do que eu,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,3,2,0,2,Falta de acesso físico: não é fácil de achar e...,Outro,Outro,NaN,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,"4 - Nem discordo, nem concordo",7 - Concordo totalmente,2 - Discordo bastante,7 - Concordo totalmente,6 - Concordo bastante,6 - Concordo bastante,6 - Concordo bastante,1 - Discordo totalmente,NaN,"Sim, podem me contatar!",NaN
2,19,1993,53200000,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Mestrado em curso,Ciências Biológicas,Sim,Não,Sim,Não,NaN,1,3,Já respondi,Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",10,Já respondi,"couvinha, monguba, margaridinha-cosmos, ararut...",17,Já respondi,0,0,Já respondi,"orelha-de-judas, ostra-rosa, porcini",3,20,Onívora - Possuo uma alimentação diversificada...,Ano,5,Ano,1,Ano,3,Familiares mais velhos que eu,Outro,Outro,"No tempo que fui vegetariana pesquisei, por co...",Meus amigos ou colegas de trabalho,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,3,7,0,0,Falta de acesso físico: não é fácil de achar e...,Falta de acesso econômico: acho esse tipo de a...,Falta de acesso físico: não é fácil de achar e...,NaN,6 - Concordo bastante,1 - Discordo totalmente,3 - Discordo pouco,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,1 - Discordo totalmente,2 - Discordo bastante,6 - Concordo bastante,7 - Concordo totalmente,NaN,NaN,NaN,NaN,NaN,"Sim, podem me contatar!",NaN
3,20,1996,59078350,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação concluída,Ecologia,Sim,Sim,Sim,Não,NaN,2,5,Durante meu envolvimento com a Horta Comunitár...,Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",10,"Mastruz, couvinha, beldroega, cariru, bredo, c...","mastruz, couvinha, major-gomes, caruru, chanan...",11,"Nori, wakame, kombu, hijiki",hijiki,1,"Shimeji, Champignon, Shitake, Portobello",0,0,12,Vegana - Não me alimento de nenhum produto que...,Ano,3,Ano,3,Ano,3,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,1,1,0,0,Falta de acesso físico: não é fácil de achar e...,Falta de acesso físico: não é fácil de achar e...,Falta de acesso físico: não é fácil de achar e...,NaN,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,"4 - Nem discordo, nem concordo",5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,5 - Concordo pouco,3 - Discordo pouco,Experimentar alimentos novos e sabores diferen...,"Sim, podem me contatar!",NaN
4,21,1994,59054831,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Doutorado em curso,Nutrição,Sim,Sim,Sim,Não,NaN,2,5,Respondido anteriormente.,Nori,Beldroega,Não sei,Shitake,Portobello,Não sei,Não sei,Taioba,Shimeji,Mangaba,7,Alga,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",7,Respondido anteriormente.,"couvinha, major-gomes, urucum, moringa, ora-pr...",11,Respondido anteriormente.,0,0,Respondido anteriormente.,0,0,11,Onívora - Possuo uma alimentação diversificada...,Ano,5,Ano,10,Semana,2,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,5,11,3,5,Outro,Falta de acesso econômico: acho esse tipo de a...,Outro,"Gosto, mas não tenho o hábito de fazer prepara...",6 - Concordo bastante,1 - Discordo totalmente,2 - Discordo bastante,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,2 - Discordo bastante,3 - Discordo pouco,6 - Concordo bastante,7 - Concordo totalmente,2 - Discordo bastante,6 - Concordo bastante,6 - Concordo bastante,2 - Discordo bastante,Minha convivência com a horta mudou muito o me...,"Sim, podem me contatar!",NaN

In [5]:
df["age"] = 2025 - df["date_birth"].astype(int)
df["age"].describe()

count    191.000000
mean      30.518325
std       12.133834
min       17.000000
25%       21.000000
50%       26.000000
75%       36.000000
max       69.000000
Name: age, dtype: float64

In [6]:
df

,id,date_birth,zip_code,urbanization_degree,gender,education_level,education_field,gardener,garden_type_communitary,garden_type_pedagogical,garden_type_other,garden_type_other_description,years_experience,frequency_experience,experience_description,g03q11,g03q12,g03q13,g03q14,g03q15,g03q16,g03q17,g03q18,g03q19,g03q20,recognition_grade,g03q21,g03q22,g03q23,g03q24,g03q25,g03q26,g03q27,g03q28,g03q29,g03q30,classification_grade,recall_plants,plants_valid,plants_total,recall_algae,algae_valid,algae_total,recall_mushrooms,mushrooms_valid,mushrooms_total,species_total,diet_type,consumption_plants_time_scale,consumption_plants_frequency,consumption_mushrooms_time_scale,consumption_mushrooms_frequency,consumption_algae_time_scale,consumption_algae_frequency,social_model_plants,social_model_mushrooms,social_model_algae,social_model_other,social_trigger_plants,social_trigger_mushrooms,social_trigger_algae,meals_friends,meals_family_older,meals_family_same_generation,meals_not_family_older,barrier_plant,barrier_mushroom,barrier_algae,barrier_other,g06q39,g06q40,g06q41,g06q42,g06q43,g06q44,g06q45,g06q46,g06q47,g06q48,g06q49,g06q50,g06q51,g06q52,extra_info,authorization_new_contact,interview_time,age
0,15,1986,59082110,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Mestrado concluído,Ciências Biológicas,Sim,Não,Sim,Não,NaN,0,1,"Participei de algumas oficinas, mas não tive c...",Nori,Não sei,Não sei,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,8,Alga,Não sei,Não sei,Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",8,"rambutan, cupuaçu, mangostim, pitaya, almeirão...","rambutan, cupuaçu, mangostim, pitaya, almeirão...",6,As algas que conheço já foram mencionadas nest...,0,0,Os cogumelos que conheço já foram mencionados ...,0,0,6,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Mês,1,Mês,2,Não consumi ou consumo esse tipo de alimento,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,NaN,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,0,0,16,0,Falta de conhecimento: não conheço esses alime...,Falta de acesso econômico: acho esse tipo de a...,Falta de acesso econômico: acho esse tipo de a...,NaN,1 - Discordo totalmente,1 - Discordo totalmente,1 - Discordo totalmente,1 - Discordo totalmente,6 - Concordo bastante,5 - Concordo pouco,1 - Discordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,5 - Concordo pouco,NaN,NaN,NaN,NaN,Me considero uma pessoa muito interessada em n...,"Sim, podem me contatar!",NaN,39
1,17,1997,59090324,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Mestrado concluído,Nutrição,Sim,Sim,Sim,Não,NaN,7,5,"Participei de atividades de ensino, pesquisa e...",Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",9,"Urucum, taioba, ora-pro-nobis,fruta pão,jambú,...","urucum, ora-pro-nóbis, fruta-pão, jambu, cubiu...",14,Alga nori,0,0,"Shitake,shimeji, portubelo, champignon",0,0,14,Flexitariano - Tenho um cardápio flexível e co...,Semana,1,Mês,1,Mês,1,Professores ou pessoas de referência mais velh...,Familiares da mesma idade ou mais novos do que eu,Não consumi ou consumo esse tipo de alimento,NaN,Familiares da mesma idade ou mais novos do que eu,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,3,2,0,2,Falta de acesso físico: não é fácil de achar e...,Outro,Outro,NaN,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,"4 - Nem discordo, nem concordo",7 - Concordo totalmente,2 - Discordo bastante,7 - Concordo totalmente,6 - Concordo bastante,6 - Concordo bastante,6 - Concordo bastante,1 - Discordo totalmente,NaN,"Sim, podem me contatar!",NaN,28
2,19,1993,53200000,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Mestrado em curso,Ciências Biológicas,Sim,Não,Sim,Não,NaN,1,3,Já respondi,Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",10,Já respondi,"couvinha, monguba, margaridinha-cosmos, ararut...",17,Já respondi,0,0,Já respondi,"orelha-de-judas, ostra-rosa, porcini",3,20,Onívora - Possuo uma alimentação diversificada...,Ano,5,Ano,1,Ano,3,Familiares mais velhos que eu,Outro,Outro,"No tempo que fui vegetariana pesquisei, por co...",Meus amigos ou colegas de trabalho,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,3,7,0,0,Falta de acesso físico: não é fácil de achar e...,Falta de acesso econômico: acho esse tipo de a...,Falta de acesso físico: não é fácil de achar e...,NaN,6 - Concordo bastante,1 - Discordo totalmente,3 - Discordo pouco,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,1 - Discordo totalmente,2 - Discordo bastante,6 - Concordo bastante,7 - Concordo totalmente,NaN,NaN,NaN,NaN,NaN,"Sim, podem me contatar!",NaN,32
3,20,1996,59078350,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação concluída,Ecologia,Sim,Sim,Sim,Não,NaN,2,5,Durante meu envolvimento com a Horta Comunitár...,Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",10,"Mastruz, couvinha, beldroega, cariru, bredo, c...","mastruz, couvinha, major-gomes, caruru, chanan...",11,"Nori, wakame, kombu, hijiki",hijiki,1,"Shimeji, Champignon, Shitake, Portobello",0,0,12,Vegana - Não me alimento de nenhum produto que...,Ano,3,Ano,3,Ano,3,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,1,1,0,0,Falta de acesso físico: não é fácil de achar e...,Falta de acesso físico: não é fácil de achar e...,Falta de acesso físico: não é fácil de achar e...,NaN,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,"4 - Nem discordo, nem concordo",5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,5 - Concordo pouco,3 - Discordo pouco,Experimentar alimentos novos e sabores diferen...,"Sim, podem me contatar!",NaN,29
4,21,1994,59054831,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Doutorado em curso,Nutrição,Sim,Sim,Sim,Não,NaN,2,5,Respondido anteriormente.,Nori,Beldroega,Não sei,Shitake,Portobello,Não sei,Não sei,Taioba,Shimeji,Mangaba,7,Alga,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",7,Respondido anteriormente.,"couvinha, major-gomes, urucum, moringa, ora-pr...",11,Respondido anteriormente.,0,0,Respondido anteriormente.,0,0,11,Onívora - Possuo uma alimentação diversificada...,Ano,5,Ano,10,Semana,2,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,5,11,3,5,Outro,Falta de acesso econômico: acho esse tipo de a...,Outro,"Gosto, mas não tenho o hábito de fazer prepara...",6 - Concordo bastante,1 - Discordo totalmente,2 - Discordo bastante,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,2 - Discordo bastante,3 - Discordo pouco,6 - Concordo bastante,7 - Concordo totalmente,2 - Discordo bastante,6 - Concordo bastante,6 - Concordo bastante,2 - Discordo bastante,Minha convivência com a horta mudou muito o me...,"Sim, podem me contatar!",NaN,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,511,2004,59074721,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação em curso,Estou cursando nutrição,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Tucumã,Não sei,Não sei,Não sei,Não sei,Taioba,Não sei,Mangaba,3,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,Não me recordo de nenhuma,NaN,0,Não conheço,NaN,0,Champingnon,NaN,0,0,Onívora - Possuo uma alimentação diversificada...,Mês,1,Nenhum,0,Nenhum,0,Meus amigos ou colegas de trabalho,Não consumi ou consumo esse tipo de alimento,Não consumi ou consumo esse tipo de alimento,NaN,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,3,3,3,0,Falta de acesso físico: não é fácil de achar e...,Outro,Outro,Não me atrai a ideia de comê-los.,5 - Concordo pouco,5 - Concordo pouco,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,"4 - Nem discordo, nem concordo",NaN,NaN,NaN,NaN,NaN,"Não, prefiro não ser contatado novamente.",NaN,21
187,512,2008,59158400,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação em curso,Nutrição,Sim,Não,Sim,Não,NaN,0,1,O primeiro contato de verdade que tive com hor...,Não sei,Não sei,Não sei,Shitake,Não sei,Não sei,Não sei,Não sei,Shimeji,Mangaba,3,Não sei,Não sei,Não sei,Cogumelo,Não sei,Não sei,Não sei,Não sei,Cogumelo,"Planta - incluindo frutas, verduras e legumes",3,Clitória.,clitória,1,Não conheço,NaN,0,Não conheço,NaN,0,1,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Nenhum,0,Nenhum,0,Não consumi ou consumo esse tipo de alimento,Não consumi ou consumo esse tipo de alimento,Não consumi ou consumo esse tipo de alimento,NaN,Professores ou pessoas de referência mais velh...,Familiares mais velhos que eu,Meus amigos ou colegas de trabalho,1,7,0,0,Falta de conhecimento: não conheço esses alime...,Falta de conhecimento: não conheço esses alime...,Falta de conhecimento: não conheço esses alime...,NaN,5 - Concordo pouco,3 - Discordo pouco,6 - Concordo bastante,"4 - Nem discordo, nem concordo",1 - Discordo totalmente,7 - Concordo totalmente,2 - Discordo bastante,5 - Concordo pouco,5 - Concordo pouco,7 - Concordo totalmente,NaN,NaN,NaN,NaN,Não me senti muito bem ao sentir a textura um ...,"Sim, podem me contatar!",NaN,17
188,513,2007,59082180,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Graduação em curso,Cursando Nutrição.,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Não sei,Não sei,Coprinellus,Não sei,Não sei,Taioba,Shimeji,Mangaba,3,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Alga,Cogumelo,Alga,Cogumelo,"Planta - incluindo frutas, verduras e legumes",Alga,"Planta - incluindo frutas, verduras e legumes",7,"Taioba, ora-pra-nos, xanana.","chanana, ora-pro-nóbis",2,Não conheço algas.,NaN,0,Não tenho conhecimento sobre cogumelos.,NaN,0,2,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Nenhum,0,Ano,10,Meus amigos ou colegas de trabalho,Familiares mais velhos que eu,Familiares da mesma idade ou mais novos do que eu,NaN,Professores ou pessoas de referência mais velh...,Familiares mais velhos que eu,Familiares mais velhos que eu,4,2,0,0,Falta de conhecimento: não conheço esses alime...,Não consumo porque não tenho intenção,Falta de acesso econômico: acho esse tipo de a...,NaN,3 - Discordo pouco,5 - Concordo pouco,2 - Discordo bastante,5 - Concordo pouco,3 - Discordo pouco,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,3 - Discordo pouco,2 - Discordo bastante,NaN,NaN,NaN,NaN,NaN,"Sim, podem me contatar!",NaN,18
189,515,2001,59151903,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação em curso,Nutrição,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Tervina,Tucumã,Não sei,Não sei,Não sei,Não sei,Taioba,Não sei,Mangaba,3,Alga,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Não sei,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,Umbu\n Seriguela\n Mangaba,"umbu, seriguela",2,Nori\n Spirulina,spirulina,1,Champignon,NaN,0,3,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Nenhum,0,Nenhum,0,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,2,0,0,0,Falta de conhecimento: não conheço esses alime...,Não consumo porque não tenho intenção,Não consumo porque não tenho intenção,NaN,1 - Discordo totalmente,"4 - Nem discordo, nem concordo",6 - Concordo bastante,2 - Discordo bastante,5 - Concordo pouco,1 - Discordo totalmente,6 - Concordo bastante,5 - Concordo pouco,3 - Discordo pouco,3 - Discordo pouco,NaN,NaN,NaN,NaN,Minha relação com alimentos negligenciados ain...,"Sim, podem me contatar!",NaN,24
190,519,1998,59088750,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Mestrado em curso,ciências sociais,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Não sei,Não sei,Coprinellus,Não sei,Não sei,Não sei,Não sei,Mangaba,1,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,não lembro,NaN,0,não conheço,NaN,0,não conheço,NaN,0,0,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Ano,2,Nenhum,0,Não consumi ou consumo esse tipo de alimento,Familiares mais velhos que eu,Não consumi ou consumo esse tipo de alimento,NaN,Familiares mais velhos que eu,Familiares mais velhos que eu,Familiares mais velhos que eu,0,3,0,0,Falta de conhecimento: não conheço esses alime...,Falta de acesso físico: não é fácil de achar e...,Falta de conhecimento: não conheço esses alime...,NaN,3 - Discordo pouco,2 - Discordo bastante,2 - Discordo bastante,5 - Concordo pouco,2 - Discordo bastante,6 - Concordo bastante,"4 - Nem discordo, nem concordo",5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,NaN,NaN,NaN,NaN,Não tenho o costume de refletir sobre hábitos ...,"Sim, podem me contatar!",NaN,27

In [7]:
from cep_utils import uf_from_cep

df["state"] = df["zip_code"].apply(uf_from_cep)
df["state"].value_counts()

state
RN    145
PB      9
RS      7
RJ      6
SP      6
PE      4
CE      4
DF      3
PI      2
SC      2
BA      1
MA      1
PR      1
Name: count, dtype: int64

In [8]:
df.query("state == 'XX'")

Empty DataFrame
Columns: [id, date_birth, zip_code, urbanization_degree, gender, education_level, education_field, gardener, garden_type_communitary, garden_type_pedagogical, garden_type_other, garden_type_other_description, years_experience, frequency_experience, experience_description, g03q11, g03q12, g03q13, g03q14, g03q15, g03q16, g03q17, g03q18, g03q19, g03q20, recognition_grade, g03q21, g03q22, g03q23, g03q24, g03q25, g03q26, g03q27, g03q28, g03q29, g03q30, classification_grade, recall_plants, plants_valid, plants_total, recall_algae, algae_valid, algae_total, recall_mushrooms, mushrooms_valid, mushrooms_total, species_total, diet_type, consumption_plants_time_scale, consumption_plants_frequency, consumption_mushrooms_time_scale, consumption_mushrooms_frequency, consumption_algae_time_scale, consumption_algae_frequency, social_model_plants, social_model_mushrooms, social_model_algae, social_model_other, social_trigger_plants, social_trigger_mushrooms, social_trigger_algae, meals_friends, meals_family_older, meals_family_same_generation, meals_not_family_older, barrier_plant, barrier_mushroom, barrier_algae, barrier_other, g06q39, g06q40, g06q41, g06q42, g06q43, g06q44, g06q45, g06q46, g06q47, g06q48, g06q49, g06q50, g06q51, g06q52, extra_info, authorization_new_contact, interview_time, age, state]
Index: []

In [9]:
regioes = {
    "AC": "North",
    "AL": "Northeast",
    "AP": "North",
    "AM": "North",
    "BA": "Northeast",
    "CE": "Northeast",
    "DF": "Central-West",
    "ES": "Southeast",
    "GO": "Central-West",
    "MA": "Northeast",
    "MT": "Central-West",
    "MS": "Central-West",
    "MG": "Southeast",
    "PA": "North",
    "PB": "Northeast",
    "PR": "South",
    "PE": "Northeast",
    "PI": "Northeast",
    "RJ": "Southeast",
    "RN": "Northeast",
    "RS": "South",
    "RO": "North",
    "RR": "North",
    "SC": "South",
    "SP": "Southeast",
    "SE": "Northeast",
    "TO": "North",
}
df["region"] = df["state"].str.upper().map(regioes)
df.region.value_counts()

region
Northeast       166
Southeast        12
South            10
Central-West      3
Name: count, dtype: int64

In [10]:
df.urbanization_degree.value_counts()

urbanization_degree
Zona urbana    183
Zona rural       8
Name: count, dtype: int64

In [11]:
df = df.query('urbanization_degree == "Zona urbana" and age >= 18')
df

,id,date_birth,zip_code,urbanization_degree,gender,education_level,education_field,gardener,garden_type_communitary,garden_type_pedagogical,garden_type_other,garden_type_other_description,years_experience,frequency_experience,experience_description,g03q11,g03q12,g03q13,g03q14,g03q15,g03q16,g03q17,g03q18,g03q19,g03q20,recognition_grade,g03q21,g03q22,g03q23,g03q24,g03q25,g03q26,g03q27,g03q28,g03q29,g03q30,classification_grade,recall_plants,plants_valid,plants_total,recall_algae,algae_valid,algae_total,recall_mushrooms,mushrooms_valid,mushrooms_total,species_total,diet_type,consumption_plants_time_scale,consumption_plants_frequency,consumption_mushrooms_time_scale,consumption_mushrooms_frequency,consumption_algae_time_scale,consumption_algae_frequency,social_model_plants,social_model_mushrooms,social_model_algae,social_model_other,social_trigger_plants,social_trigger_mushrooms,social_trigger_algae,meals_friends,meals_family_older,meals_family_same_generation,meals_not_family_older,barrier_plant,barrier_mushroom,barrier_algae,barrier_other,g06q39,g06q40,g06q41,g06q42,g06q43,g06q44,g06q45,g06q46,g06q47,g06q48,g06q49,g06q50,g06q51,g06q52,extra_info,authorization_new_contact,interview_time,age,state,region
0,15,1986,59082110,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Mestrado concluído,Ciências Biológicas,Sim,Não,Sim,Não,NaN,0,1,"Participei de algumas oficinas, mas não tive c...",Nori,Não sei,Não sei,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,8,Alga,Não sei,Não sei,Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",8,"rambutan, cupuaçu, mangostim, pitaya, almeirão...","rambutan, cupuaçu, mangostim, pitaya, almeirão...",6,As algas que conheço já foram mencionadas nest...,0,0,Os cogumelos que conheço já foram mencionados ...,0,0,6,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Mês,1,Mês,2,Não consumi ou consumo esse tipo de alimento,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,NaN,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,0,0,16,0,Falta de conhecimento: não conheço esses alime...,Falta de acesso econômico: acho esse tipo de a...,Falta de acesso econômico: acho esse tipo de a...,NaN,1 - Discordo totalmente,1 - Discordo totalmente,1 - Discordo totalmente,1 - Discordo totalmente,6 - Concordo bastante,5 - Concordo pouco,1 - Discordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,5 - Concordo pouco,NaN,NaN,NaN,NaN,Me considero uma pessoa muito interessada em n...,"Sim, podem me contatar!",NaN,39,RN,Northeast
1,17,1997,59090324,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Mestrado concluído,Nutrição,Sim,Sim,Sim,Não,NaN,7,5,"Participei de atividades de ensino, pesquisa e...",Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",9,"Urucum, taioba, ora-pro-nobis,fruta pão,jambú,...","urucum, ora-pro-nóbis, fruta-pão, jambu, cubiu...",14,Alga nori,0,0,"Shitake,shimeji, portubelo, champignon",0,0,14,Flexitariano - Tenho um cardápio flexível e co...,Semana,1,Mês,1,Mês,1,Professores ou pessoas de referência mais velh...,Familiares da mesma idade ou mais novos do que eu,Não consumi ou consumo esse tipo de alimento,NaN,Familiares da mesma idade ou mais novos do que eu,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,3,2,0,2,Falta de acesso físico: não é fácil de achar e...,Outro,Outro,NaN,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,"4 - Nem discordo, nem concordo",7 - Concordo totalmente,2 - Discordo bastante,7 - Concordo totalmente,6 - Concordo bastante,6 - Concordo bastante,6 - Concordo bastante,1 - Discordo totalmente,NaN,"Sim, podem me contatar!",NaN,28,RN,Northeast
2,19,1993,53200000,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Mestrado em curso,Ciências Biológicas,Sim,Não,Sim,Não,NaN,1,3,Já respondi,Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",10,Já respondi,"couvinha, monguba, margaridinha-cosmos, ararut...",17,Já respondi,0,0,Já respondi,"orelha-de-judas, ostra-rosa, porcini",3,20,Onívora - Possuo uma alimentação diversificada...,Ano,5,Ano,1,Ano,3,Familiares mais velhos que eu,Outro,Outro,"No tempo que fui vegetariana pesquisei, por co...",Meus amigos ou colegas de trabalho,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,3,7,0,0,Falta de acesso físico: não é fácil de achar e...,Falta de acesso econômico: acho esse tipo de a...,Falta de acesso físico: não é fácil de achar e...,NaN,6 - Concordo bastante,1 - Discordo totalmente,3 - Discordo pouco,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,1 - Discordo totalmente,2 - Discordo bastante,6 - Concordo bastante,7 - Concordo totalmente,NaN,NaN,NaN,NaN,NaN,"Sim, podem me contatar!",NaN,32,PE,Northeast
3,20,1996,59078350,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação concluída,Ecologia,Sim,Sim,Sim,Não,NaN,2,5,Durante meu envolvimento com a Horta Comunitár...,Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",10,"Mastruz, couvinha, beldroega, cariru, bredo, c...","mastruz, couvinha, major-gomes, caruru, chanan...",11,"Nori, wakame, kombu, hijiki",hijiki,1,"Shimeji, Champignon, Shitake, Portobello",0,0,12,Vegana - Não me alimento de nenhum produto que...,Ano,3,Ano,3,Ano,3,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,1,1,0,0,Falta de acesso físico: não é fácil de achar e...,Falta de acesso físico: não é fácil de achar e...,Falta de acesso físico: não é fácil de achar e...,NaN,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,"4 - Nem discordo, nem concordo",5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,5 - Concordo pouco,3 - Discordo pouco,Experimentar alimentos novos e sabores diferen...,"Sim, podem me contatar!",NaN,29,RN,Northeast
4,21,1994,59054831,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Doutorado em curso,Nutrição,Sim,Sim,Sim,Não,NaN,2,5,Respondido anteriormente.,Nori,Beldroega,Não sei,Shitake,Portobello,Não sei,Não sei,Taioba,Shimeji,Mangaba,7,Alga,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",7,Respondido anteriormente.,"couvinha, major-gomes, urucum, moringa, ora-pr...",11,Respondido anteriormente.,0,0,Respondido anteriormente.,0,0,11,Onívora - Possuo uma alimentação diversificada...,Ano,5,Ano,10,Semana,2,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,5,11,3,5,Outro,Falta de acesso econômico: acho esse tipo de a...,Outro,"Gosto, mas não tenho o hábito de fazer prepara...",6 - Concordo bastante,1 - Discordo totalmente,2 - Discordo bastante,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,2 - Discordo bastante,3 - Discordo pouco,6 - Concordo bastante,7 - Concordo totalmente,2 - Discordo bastante,6 - Concordo bastante,6 - Concordo bastante,2 - Discordo bastante,Minha convivência com a horta mudou muito o me...,"Sim, podem me contatar!",NaN,31,RN,Northeast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,509,2007,59072433,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Graduação em curso,NUTRIÇÃO,Sim,Sim,Não,Não,NaN,1,2,Produção de uma horta para um projeto estudantil,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,Taioba,Não sei,Mangaba,2,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",1,pitomba,pitomba,1,não lembro,NaN,0,não lembro,NaN,0,1,Onívora - Possuo uma alimentação diversificada...,Semana,1,Ano,1,Nenhum,0,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Não consumi ou consumo esse tipo de alimento,NaN,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,1,5,0,0,Falta de conhecimento: não conheço esses alime...,Falta de conhecimento: não conheço esses alime...,Falta de conhecimento: não conheço esses alime...,NaN,"4 - Nem discordo, nem concordo",2 - Discordo bastante,6 - Concordo bastante,6 - Concordo bastante,3 - Discordo pouco,7 - Concordo totalmente,2 - Discordo bastante,"4 - Nem discordo, nem concordo",7 - Concordo totalmente,6 - Concordo bastante,NaN,NaN,NaN,NaN,NaN,"Não, prefiro não ser contatado novamente.",NaN,18,RN,Northeast
186,511,2004,59074721,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação em curso,Estou cursando nutrição,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Tucumã,Não sei,Não sei,Não sei,Não sei,Taioba,Não sei,Mangaba,3,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,Não me recordo de nenhuma,NaN,0,Não conheço,NaN,0,Champingnon,NaN,0,0,Onívora - Possuo uma alimentação diversificada...,Mês,1,Nenhum,0,Nenhum,0,Meus amigos ou colegas de trabalho,Não consumi ou consumo esse tipo de alimento,Não consumi ou consumo esse tipo de alimento,NaN,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,3,3,3,0,Falta de acesso físico: não é fácil de achar e...,Outro,Outro,Não me atrai a ideia de comê-los.,5 - Concordo pouco,5 - Concordo pouco,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,"4 - Nem discordo, nem concordo",NaN,NaN,NaN,NaN,NaN,"Não, prefiro não ser contatado novamente.",NaN,21,RN,Northeast
188,513,2007,59082180,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Graduação em curso,Cursando Nutrição.,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Não sei,Não sei,Coprinellus,Não sei,Não sei,Taioba,Shimeji,Mangaba,3,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Alga,Cogumelo,Alga,Cogumelo,"Planta - incluindo frutas, verduras e legumes",Alga,"Planta - incluindo frutas, verduras e legumes",7,"Taioba, ora-pra-nos, xanana.","chanana, ora-pro-nóbis",2,Não conheço algas.,NaN,0,Não tenho conhecimento sobre cogumelos.,NaN,0,2,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Nenhum,0,Ano,10,Meus amigos ou colegas de trabalho,Familiares mais velhos que eu,Familiares da mesma idade ou mais novos do que eu,NaN,Professores ou pessoas de referência mais velh...,Familiares mais velhos que eu,Familiares mais velhos que eu,4,2,0,0,Falta de conhecimento: não conheço esses alime...,Não consumo porque não tenho intenção,Falta de acesso econômico: acho esse tipo de a...,NaN,3 - Discordo pouco,5 - Concordo pouco,2 - Discordo bastante,5 - Concordo pouco,3 - Discordo pouco,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,3 - Discordo pouco,2 - Discordo bastante,NaN,NaN,NaN,NaN,NaN,"Sim, podem me contatar!",NaN,18,RN,Northeast
189,515,2001,59151903,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação em curso,Nutrição,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Tervina,Tucumã,Não sei,Não sei,Não sei,Não sei,Taioba,Não sei,Mangaba,3,Alga,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Não sei,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,Umbu\n Seriguela\n Mangaba,"umbu, seriguela",2,Nori\n Spirulina,spirulina,1,Champignon,NaN,0,3,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Nenhum,0,Nenhum,0,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,2,0,0,0,Falta de conhecimento: não conheço esses alime...,Não consumo porque não tenho intenção,Não consumo porque não tenho intenção,NaN,1 - Discordo totalmente,"4 - Nem discordo, nem concordo",6 - Concordo bastante,2 - Discordo bastante,5 - Concordo pouco,1 - Discordo totalmente,6 - Concordo bastante,5 - Concordo pouco,3 - Discordo pouco,3 - Discordo pouco,NaN,NaN,NaN,NaN,Minha relação com alimentos negligenciados ain...,"Sim, podem me contatar!",NaN,24,RN,Northeast
190,519,1998,59088750,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Mestrado em curso,ciências sociais,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Não sei,Não sei,Coprinellus,Não sei,Não sei,Não sei,Não sei,Mangaba,1,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,não lembro,NaN,0,não conheço,NaN,0,não conheço,NaN,0,0,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Ano,2,Nenhum,0,Não consumi ou consumo esse tipo de alimento,Familiares mais velhos que eu,Não consumi ou consumo esse tipo de alimento,NaN,Familiares mais velhos que eu,Familiares mais velhos que eu,Familiares mais velhos que eu,0,3,0,0,Falta de conhecimento: não conheço esses alime...,Falta de acesso físico: não é fácil de achar e...,Falta de conhecimento: não conheço esses alime...,NaN,3 - Discordo pouco,2 - Discordo bastante,2 - Discordo bastante,5 - Concordo pouco,2 - Discordo bastante,6 - Concordo bastante,"4 - Nem discordo, nem concordo",5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,NaN,NaN,NaN,NaN,Não tenho o costume de refletir sobre hábitos ...,"Sim, podem me contatar!",NaN,27,RN,Northeast

In [12]:
df.reset_index(drop=True, inplace=True)

In [13]:
# save to json
df.to_json("../data/processed/data_cleaned.json", orient="records", lines=True)
df

,id,date_birth,zip_code,urbanization_degree,gender,education_level,education_field,gardener,garden_type_communitary,garden_type_pedagogical,garden_type_other,garden_type_other_description,years_experience,frequency_experience,experience_description,g03q11,g03q12,g03q13,g03q14,g03q15,g03q16,g03q17,g03q18,g03q19,g03q20,recognition_grade,g03q21,g03q22,g03q23,g03q24,g03q25,g03q26,g03q27,g03q28,g03q29,g03q30,classification_grade,recall_plants,plants_valid,plants_total,recall_algae,algae_valid,algae_total,recall_mushrooms,mushrooms_valid,mushrooms_total,species_total,diet_type,consumption_plants_time_scale,consumption_plants_frequency,consumption_mushrooms_time_scale,consumption_mushrooms_frequency,consumption_algae_time_scale,consumption_algae_frequency,social_model_plants,social_model_mushrooms,social_model_algae,social_model_other,social_trigger_plants,social_trigger_mushrooms,social_trigger_algae,meals_friends,meals_family_older,meals_family_same_generation,meals_not_family_older,barrier_plant,barrier_mushroom,barrier_algae,barrier_other,g06q39,g06q40,g06q41,g06q42,g06q43,g06q44,g06q45,g06q46,g06q47,g06q48,g06q49,g06q50,g06q51,g06q52,extra_info,authorization_new_contact,interview_time,age,state,region
0,15,1986,59082110,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Mestrado concluído,Ciências Biológicas,Sim,Não,Sim,Não,NaN,0,1,"Participei de algumas oficinas, mas não tive c...",Nori,Não sei,Não sei,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,8,Alga,Não sei,Não sei,Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",8,"rambutan, cupuaçu, mangostim, pitaya, almeirão...","rambutan, cupuaçu, mangostim, pitaya, almeirão...",6,As algas que conheço já foram mencionadas nest...,0,0,Os cogumelos que conheço já foram mencionados ...,0,0,6,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Mês,1,Mês,2,Não consumi ou consumo esse tipo de alimento,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,NaN,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,Familiares da mesma idade ou mais novos do que eu,0,0,16,0,Falta de conhecimento: não conheço esses alime...,Falta de acesso econômico: acho esse tipo de a...,Falta de acesso econômico: acho esse tipo de a...,NaN,1 - Discordo totalmente,1 - Discordo totalmente,1 - Discordo totalmente,1 - Discordo totalmente,6 - Concordo bastante,5 - Concordo pouco,1 - Discordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,5 - Concordo pouco,NaN,NaN,NaN,NaN,Me considero uma pessoa muito interessada em n...,"Sim, podem me contatar!",NaN,39,RN,Northeast
1,17,1997,59090324,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Mestrado concluído,Nutrição,Sim,Sim,Sim,Não,NaN,7,5,"Participei de atividades de ensino, pesquisa e...",Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",9,"Urucum, taioba, ora-pro-nobis,fruta pão,jambú,...","urucum, ora-pro-nóbis, fruta-pão, jambu, cubiu...",14,Alga nori,0,0,"Shitake,shimeji, portubelo, champignon",0,0,14,Flexitariano - Tenho um cardápio flexível e co...,Semana,1,Mês,1,Mês,1,Professores ou pessoas de referência mais velh...,Familiares da mesma idade ou mais novos do que eu,Não consumi ou consumo esse tipo de alimento,NaN,Familiares da mesma idade ou mais novos do que eu,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,3,2,0,2,Falta de acesso físico: não é fácil de achar e...,Outro,Outro,NaN,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,"4 - Nem discordo, nem concordo",7 - Concordo totalmente,2 - Discordo bastante,7 - Concordo totalmente,6 - Concordo bastante,6 - Concordo bastante,6 - Concordo bastante,1 - Discordo totalmente,NaN,"Sim, podem me contatar!",NaN,28,RN,Northeast
2,19,1993,53200000,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Mestrado em curso,Ciências Biológicas,Sim,Não,Sim,Não,NaN,1,3,Já respondi,Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",10,Já respondi,"couvinha, monguba, margaridinha-cosmos, ararut...",17,Já respondi,0,0,Já respondi,"orelha-de-judas, ostra-rosa, porcini",3,20,Onívora - Possuo uma alimentação diversificada...,Ano,5,Ano,1,Ano,3,Familiares mais velhos que eu,Outro,Outro,"No tempo que fui vegetariana pesquisei, por co...",Meus amigos ou colegas de trabalho,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,3,7,0,0,Falta de acesso físico: não é fácil de achar e...,Falta de acesso econômico: acho esse tipo de a...,Falta de acesso físico: não é fácil de achar e...,NaN,6 - Concordo bastante,1 - Discordo totalmente,3 - Discordo pouco,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,1 - Discordo totalmente,2 - Discordo bastante,6 - Concordo bastante,7 - Concordo totalmente,NaN,NaN,NaN,NaN,NaN,"Sim, podem me contatar!",NaN,32,PE,Northeast
3,20,1996,59078350,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação concluída,Ecologia,Sim,Sim,Sim,Não,NaN,2,5,Durante meu envolvimento com a Horta Comunitár...,Nori,Beldroega,Tucumã,Shitake,Portobello,Wakame,Kombu,Taioba,Shimeji,Mangaba,10,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Cogumelo,Cogumelo,Alga,Alga,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",10,"Mastruz, couvinha, beldroega, cariru, bredo, c...","mastruz, couvinha, major-gomes, caruru, chanan...",11,"Nori, wakame, kombu, hijiki",hijiki,1,"Shimeji, Champignon, Shitake, Portobello",0,0,12,Vegana - Não me alimento de nenhum produto que...,Ano,3,Ano,3,Ano,3,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,1,1,0,0,Falta de acesso físico: não é fácil de achar e...,Falta de acesso físico: não é fácil de achar e...,Falta de acesso físico: não é fácil de achar e...,NaN,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,"4 - Nem discordo, nem concordo",5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,2 - Discordo bastante,6 - Concordo bastante,5 - Concordo pouco,3 - Discordo pouco,Experimentar alimentos novos e sabores diferen...,"Sim, podem me contatar!",NaN,29,RN,Northeast
4,21,1994,59054831,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Doutorado em curso,Nutrição,Sim,Sim,Sim,Não,NaN,2,5,Respondido anteriormente.,Nori,Beldroega,Não sei,Shitake,Portobello,Não sei,Não sei,Taioba,Shimeji,Mangaba,7,Alga,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Cogumelo,"Planta - incluindo frutas, verduras e legumes",7,Respondido anteriormente.,"couvinha, major-gomes, urucum, moringa, ora-pr...",11,Respondido anteriormente.,0,0,Respondido anteriormente.,0,0,11,Onívora - Possuo uma alimentação diversificada...,Ano,5,Ano,10,Semana,2,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,5,11,3,5,Outro,Falta de acesso econômico: acho esse tipo de a...,Outro,"Gosto, mas não tenho o hábito de fazer prepara...",6 - Concordo bastante,1 - Discordo totalmente,2 - Discordo bastante,7 - Concordo totalmente,1 - Discordo totalmente,7 - Concordo totalmente,2 - Discordo bastante,3 - Discordo pouco,6 - Concordo bastante,7 - Concordo totalmente,2 - Discordo bastante,6 - Concordo bastante,6 - Concordo bastante,2 - Discordo bastante,Minha convivência com a horta mudou muito o me...,"Sim, podem me contatar!",NaN,31,RN,Northeast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,509,2007,59072433,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Graduação em curso,NUTRIÇÃO,Sim,Sim,Não,Não,NaN,1,2,Produção de uma horta para um projeto estudantil,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,Taioba,Não sei,Mangaba,2,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",1,pitomba,pitomba,1,não lembro,NaN,0,não lembro,NaN,0,1,Onívora - Possuo uma alimentação diversificada...,Semana,1,Ano,1,Nenhum,0,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Não consumi ou consumo esse tipo de alimento,NaN,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,Professores ou pessoas de referência mais velh...,1,5,0,0,Falta de conhecimento: não conheço esses alime...,Falta de conhecimento: não conheço esses alime...,Falta de conhecimento: não conheço esses alime...,NaN,"4 - Nem discordo, nem concordo",2 - Discordo bastante,6 - Concordo bastante,6 - Concordo bastante,3 - Discordo pouco,7 - Concordo totalmente,2 - Discordo bastante,"4 - Nem discordo, nem concordo",7 - Concordo totalmente,6 - Concordo bastante,NaN,NaN,NaN,NaN,NaN,"Não, prefiro não ser contatado novamente.",NaN,18,RN,Northeast
176,511,2004,59074721,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação em curso,Estou cursando nutrição,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Tucumã,Não sei,Não sei,Não sei,Não sei,Taioba,Não sei,Mangaba,3,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,Não me recordo de nenhuma,NaN,0,Não conheço,NaN,0,Champingnon,NaN,0,0,Onívora - Possuo uma alimentação diversificada...,Mês,1,Nenhum,0,Nenhum,0,Meus amigos ou colegas de trabalho,Não consumi ou consumo esse tipo de alimento,Não consumi ou consumo esse tipo de alimento,NaN,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,3,3,3,0,Falta de acesso físico: não é fácil de achar e...,Outro,Outro,Não me atrai a ideia de comê-los.,5 - Concordo pouco,5 - Concordo pouco,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,5 - Concordo pouco,"4 - Nem discordo, nem concordo",NaN,NaN,NaN,NaN,NaN,"Não, prefiro não ser contatado novamente.",NaN,21,RN,Northeast
177,513,2007,59082180,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Graduação em curso,Cursando Nutrição.,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Não sei,Não sei,Coprinellus,Não sei,Não sei,Taioba,Shimeji,Mangaba,3,Alga,"Planta - incluindo frutas, verduras e legumes","Planta - incluindo frutas, verduras e legumes",Alga,Cogumelo,Alga,Cogumelo,"Planta - incluindo frutas, verduras e legumes",Alga,"Planta - incluindo frutas, verduras e legumes",7,"Taioba, ora-pra-nos, xanana.","chanana, ora-pro-nóbis",2,Não conheço algas.,NaN,0,Não tenho conhecimento sobre cogumelos.,NaN,0,2,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Nenhum,0,Ano,10,Meus amigos ou colegas de trabalho,Familiares mais velhos que eu,Familiares da mesma idade ou mais novos do que eu,NaN,Professores ou pessoas de referência mais velh...,Familiares mais velhos que eu,Familiares mais velhos que eu,4,2,0,0,Falta de conhecimento: não conheço esses alime...,Não consumo porque não tenho intenção,Falta de acesso econômico: acho esse tipo de a...,NaN,3 - Discordo pouco,5 - Concordo pouco,2 - Discordo bastante,5 - Concordo pouco,3 - Discordo pouco,5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,3 - Discordo pouco,2 - Discordo bastante,NaN,NaN,NaN,NaN,NaN,"Sim, podem me contatar!",NaN,18,RN,Northeast
178,515,2001,59151903,Zona urbana,Mulher cis - pessoa que nasceu com sexo femini...,Graduação em curso,Nutrição,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Tervina,Tucumã,Não sei,Não sei,Não sei,Não sei,Taioba,Não sei,Mangaba,3,Alga,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Não sei,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,Umbu\n Seriguela\n Mangaba,"umbu, seriguela",2,Nori\n Spirulina,spirulina,1,Champignon,NaN,0,3,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Nenhum,0,Nenhum,0,Professores ou pessoas de referência mais velh...,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,NaN,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,Meus amigos ou colegas de trabalho,2,0,0,0,Falta de conhecimento: não conheço esses alime...,Não consumo porque não tenho intenção,Não consumo porque não tenho intenção,NaN,1 - Discordo totalmente,"4 - Nem discordo, nem concordo",6 - Concordo bastante,2 - Discordo bastante,5 - Concordo pouco,1 - Discordo totalmente,6 - Concordo bastante,5 - Concordo pouco,3 - Discordo pouco,3 - Discordo pouco,NaN,NaN,NaN,NaN,Minha relação com alimentos negligenciados ain...,"Sim, podem me contatar!",NaN,24,RN,Northeast
179,519,1998,59088750,Zona urbana,Homem cis - pessoa que nasceu com sexo masculi...,Mestrado em curso,ciências sociais,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Não sei,Não sei,Não sei,Não sei,Coprinellus,Não sei,Não sei,Não sei,Não sei,Mangaba,1,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,Cogumelo,Não sei,Não sei,"Planta - incluindo frutas, verduras e legumes",Não sei,"Planta - incluindo frutas, verduras e legumes",4,não lembro,NaN,0,não conheço,NaN,0,não conheço,NaN,0,0,Onívora - Possuo uma alimentação diversificada...,Nenhum,0,Ano,2,Nenhum,0,Não consumi ou consumo esse tipo de alimento,Familiares mais velhos que eu,Não consumi ou consumo esse tipo de alimento,NaN,Familiares mais velhos que eu,Familiares mais velhos que eu,Familiares mais velhos que eu,0,3,0,0,Falta de conhecimento: não conheço esses alime...,Falta de acesso físico: não é fácil de achar e...,Falta de conhecimento: não conheço esses alime...,NaN,3 - Discordo pouco,2 - Discordo bastante,2 - Discordo bastante,5 - Concordo pouco,2 - Discordo bastante,6 - Concordo bastante,"4 - Nem discordo, nem concordo",5 - Concordo pouco,5 - Concordo pouco,6 - Concordo bastante,NaN,NaN,NaN,NaN,Não tenho o costume de refletir sobre hábitos ...,"Sim, podem me contatar!",NaN,27,RN,Northeast